### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#426]
Tracking issue about the project documentation.

- [x] Project root readme (!)
- [x] API documentation. Check content of the guide and update. Readme link
- [x] Panic abort #465
- [x] `nstar` readme #817 
- [x] `stress` readme #817 
- [X] API schema #453
- [X] Check `cargo doc` output. See #394
- [X] Manifest documentation. Check content of the guide.
- [X] Manifest schema? Describe the manifest in a schema #453
- [X] Readme structure. See [doc](https://github.com/esrlabs/northstar/tree/doc) branch.
- [X] Runtime configuration `northstar::runtime::config::Config` and `northstar.toml`
- [x] Add linting for markdown files #455
- [x] Mount option #545
- [x] `seccomp-util` readme
- [x] `sextant` readme
